---
- name: Install Dependencies
  yum: name={{ item }} state=latest
  with_items: "{{ phantomjs_dependencies }}"

- name: Get PhantomJS
  get_url:
    url:
    dest: /tmp

- name: Unpack PhantomJS
  unarchive:
    src=https://github.com/ariya/phantomjs/archive/{{ phantomjs_version }}.tar.gz
    remote_src=yes
    dest=/tmp

