---
- name: Install Dependencies
  yum: name={{ item }} state=latest
  with_items: "{{ phantomjs_dependencies }}"

- name: Get PhantomJS
  get_url:
    url=https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-{{ phantomjs_version }}-linux-x86_64.tar.bz2
    dest=/tmp

- name: Unpack PhantomJS
  unarchive:
    src=/tmp/phantomjs-{{ phantomjs_version }}-linux-x86_64.tar.bz2
    copy=no
    dest=/tmp

- name: Move PhantomJS Into Place
  copy:
    src=/tmp/phantomjs-{{ phantomjs_version }}-linux-x86_64/bin/phantomjs
    dest=/usr/local/bin
    mode=0755

- name: Kill Install Dir
  file:
    path=/tmp/phantomjs-{{ phantomjs_version }}-linux-x86_64
    state=absent
