---
- name: Install Dependencies
  yum: name={{ item }} state=latest
  with_items: "{{ phantomjs_dependencies }}"

- name: Unpack PhantomJS
  unarchive:
    src=https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-{{ phantomjs_version }}-linux-x86_64.tar.bz2
    remote_src=yes
    dest=/tmp

- name: Move PhantomJS Into Place
  copy:
    src=/tmp/phantomjs-{{ phantomjs_version }}-linux-x86_64/bin/phantomjs
    dest=/usr/local/bin
    mode=0755
    owner=root
    group=root
